name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: sudo xcrun xcode-select -s /Applications/Xcode_14.2.app
    - name: Test
      run: |
            pushd Sources
            simruntime=$(xcrun simctl list runtimes -j | jq '.runtimes[0].identifier')
            prefix=".devices."
            suffix="[0].udid"
            deviceid=$(xcrun simctl list -j | jq -r "$prefix$simruntime$suffix")
            xcrun xcodebuild test -scheme Whiff -sdk iphonesimulator -destination "platform=iOS Simulator,id=$deviceid"
            popd
